name: Docker

on:
  workflow_dispatch:
  push:
    branches: [ main ]


env:
  DOCKER_HUB_USER: "${{ secrets.DOCKER_HUB_USER }}"
  DOCKER_HUB_PASSWORD: "${{ secrets.DOCKER_HUB_PASSWORD }}"
  DOCKER_HUB: "${{ secrets.DOCKER_HUB }}"
jobs:

  build:
    name: Pull
    runs-on: ubuntu-latest
    steps:
    - name: Before freeing up disk space
      run: |
        echo "Before freeing up disk space"
        echo "=============================================================================="
        df -hT
        echo "=============================================================================="

    - name: List Docker HUB Image Tag
      run: |
        TOKEN=$(curl -sSL -u "$DOCKER_HUB_USER:$DOCKER_HUB_PASSWORD" https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/nginx:pull | jq -r '.token')
        #echo $TOKEN
        while IFS= read -r line || [ -n "$line" ]; do
            # 忽略空行与注释
            [[ -z "$line" ]] && continue
            if echo "$line" | grep -q '^\s*#'; then
                continue
            fi
        
            echo "docker search tag $line"
            curl -sSL -H "Authorization: Bearer $TOKEN" https://registry.hub.docker.com/v2/repositories/$line/tags?page_size=100 | jq -r '.results[].name'
        done < images.txt
